version: '2.1'

services:
  Redis:
    image: redis:latest
    ports:
    - 6379:6379
    volumes:
    - ./data:/data
    networks:
    - serve

  node:
    build: ./docker/node
    ports:
    - 8000:8000
    volumes:
    - ./:/usr/src/app
    networks:
    - serve

networks:
  serve:
